- hosts: all
  remote_user: ubuntu
  become: true
  tasks:
  - name: Installing prerequisites for docker
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
      

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
      state: present

  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      

  - service:
      name: docker
      state: restarted
